---
- name: Delete unauthorized images
  os_image:
    auth_type: "{{ os_images_auth_type }}"
    auth: "{{ os_images_auth }}"
    cacert: "{{ os_images_cacert | default(omit) }}"
    interface: "{{ os_images_interface | default(omit, true) }}"
    name: "{{ item.name }}"
    state: absent
  with_items: "{{ os_images_whitelist }}"
