---
- name: Ensure old images are retired
  command: >
            {{ os_images_venv }}/bin/openstack image set {{ item.name }} --name {{ item.name }}.{{ extension }}
  vars:
    extension: "{{ ansible_date_time.date }}"
  with_items:
    - "{{ os_images_list }}"
  when: item.rename_image | default(os_images_promote) | bool
  environment: "{{ os_images_venv }}"

- name: Ensure new images are promoted
  command: >
            {{ os_images_venv }}/bin/openstack image set {{ item.name }}-{{ extension }} --name {{ item.name[:-3] }}
  vars:
    extension: "rc"
  with_items:
    - "{{ os_images_list }}"
  when: item.rename_image | default(os_images_promote) | bool
  environment: "{{ os_images_venv }}"